#!/bin/bash

REPOSITORY=spacegame

TARGET="/home/pi/builds/$REPOSITORY"
GIT_DIR="/home/pi/repos/$REPOSITORY.git"
BRANCH="master"

while read oldrev newrev ref
do
  # only checking out the master (or whatever branch you would like to deploy)
  if [ "$ref" = "refs/heads/$BRANCH" ];
    then
      echo "Ref $ref received. Deploying ${BRANCH} branch to production..."
      git --work-tree=$TARGET --git-dir=$GIT_DIR checkout -f $BRANCH
      cd $TARGET
      mix deps.get
      npm ci --prefix assets
      mix ecto.setup
      #mix ecto.migrate
      #MIX_ENV=prod mix release
      #cp _build/prod/rel/spacegame/bin/spacegame ~/www
    else
      echo "Ref $ref received. Doing nothing: only the ${BRANCH} branch will be deployed"
    fi
done
